### ISSUE TITLE
Possible to send a dashboard variable to the feed URL as query parameter

### ISSUE THREAD

**Issue by Nkmol** [VolkovLabs/volkovlabs-rss-datasource#42]
**Request**
I am not sure if this is already possible, but it would be great to set a dashboard variable to the feed URL.

**Example**

```yml
datasources:
  - name: 'Feed'
    type: volkovlabs-rss-datasource
    version: 1
    jsonData:
      feed: http://my-api/resource/activity?parameter=${value}
```

----

I believe this might be possible through https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-variables/#interpolate-variables-in-data-source-plugins?
